@Restaurants_Api_HostAddress = http://localhost:5204

@token = CfDJ8NWx4kvxRyZKrLy7i82zb4FX-4jTXX3XmIaIAGIQHiydWkP7r2EZPWkwGtNyi4DhuannygaTX73pSAHeK7Qhe7I_EouCvFj8OX7z9p-_pWYmSKfruRKy85ed5Wz5VJZOblhcm-6PTHiIqRKLWiDzOwP22OKFbCXGQG9OMYyEiy_sbMMgW3-6JXsEuDI1Do4fHGP3ZGz76LykEnc3OS09x70Ufrhu2UdGYax57WgDuJssyFic_yoAUHYs0-et0qIGFgJcUeWvxwE91xL0mmsJb12J_Xne7NMWNiyr840d6P548OAZrgDs4ecTJiyvGG5nJCIty8UxVWtbGl9l7rrUG-labv7fRuymFCeIXjz5PlSTdYuQ00OiTgAIP6hm-VAbseN2ZscE2bqnUB6P5cxlLLBlOrpb14EPlnruPtbTQTfT26H-kTg9-WvEAqktI8vZ-4ZvKy4uzbH82RFIC1nWMH_UQpZQuOBonU_iS2Dw7KPqgBYzRI_ktuy9UHV9acapnOSGMH_VkYpb5xfEWAy-VoSBy-MFNGzmSvJHMo8QzjMXhywlBeAFT3kc9piqRSGznhoqPXfEc2rB5OAjsTLdt4nAHKgRJeZruezh_s2Q9oP9G3U_nTH_7RnjecWuCcsxBTe-tPx0AgO3edWPE5ne9Ht_ksoIPO7ZNK4BUNP8dNsDMiesyuZnPfD3xdgVIA8RvXYUnmC30stanZouudSbqVD7dW5m4hU6oCXRWdXKNl-6d_T-7lodnmrg1NnNPjjuInR-bb1fOce5RXP7JszDoV05UYw2MTu2tliNabAqZMFw

###
GET {{Restaurants_Api_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Accept: application/json

###
GET {{Restaurants_Api_HostAddress}}/api/restaurants/2
Authorization: Bearer {{token}}
Content-Type: application/json


###
POST {{Restaurants_Api_HostAddress}}/api/restaurants
Content-Type: application/json

###
PATCH {{Restaurants_Api_HostAddress}}/api/restaurants/4
Accept: application/json

### ------ Identity ----------

###
POST {{Restaurants_Api_HostAddress}}/api/identity/login
Content-Type: application/json

{
"email" : "owner@gmail.com",
"password" : "Password1!"
}


###
PATCH {{Restaurants_Api_HostAddress}}/api/identity/user
Authorization: Bearer {{token}}
Content-Type: application/json


{
  "Nationality" : "Malaysia",
  "DateOfBirth" : "2026-02-04"
}


