@Restaurants_Api_HostAddress = http://localhost:5204

@token = CfDJ8NWx4kvxRyZKrLy7i82zb4EmgeysD76XPAxYuKXyGePyHXn55lttEXXzS6SssUm_xmDv7FsRDgGo3BZFFDqnc1ms0EP2rNiAzpyMkbP9WsKu33grvU_bJcL4Nc-lQoaO9xraBA6bqYDLxYBGS7B1zkox6IvWO2JzAPE8wDFQf49p4IbctxJXr-hTwq18bXK7hpEQtssGx2402IwoZWxiCZpqv49e6Zmyb1BwDH5WE1f5RwmTyf-k3d_w1nU1XKXj6PmXCoCOo0TgaFRH7wTdpaDcjsxx4uELJxh2exp0uXFryWppVXZLp9z32B1LjJRB0lJd_eI8ptIYAkvygNqodp4-InaOKDrTcZ2V3rxVXnD3WaRQzZK09MdkGEaAdP4pjkBGLjkwjWWhZZabotJa2oveypKH4TF6D3wAk3QNXYYmD0tkuE-pwaRARCzX0hR2To-8SXV9Ms7vakwjiPYtZ_4J17lkEQbWAQexeK_fmMFDuB9yZyMsFs8qs2cSA_4eTVPdeTOCcW6VBc-Fo5SDyKXg20EBW9IPNR10O666MQycmp7vfFwXte-kDIRsDZF3RBhAQwRXNjDLl4WzccYLQDsb2F4DX74e9OctNYAzyDg_-sYfnQARCgTVbkIPL67Hp-skFR28_bsXuyj7B5IybuQXA0_cUNfGUxelaOybvBd22CvKMiVKWT7Rrfl8BaNqZVTvTppj67sGp2tsQE5VDjl0E6IaYFwzOu6RYEDOLMthNy6T2yj-VBcdbPNSCw645Sc95uEQJ_7LL3_W92dN2LUieVmO2Ypik3NsbwQOpllN

### -------- Restaurant ---------------

### Get all restaurants
GET {{Restaurants_Api_HostAddress}}/api/restaurants?pageSize=5&pageNumber=1
//Authorization: Bearer {{token}}
Accept: application/json

### Get restaurant based on filtering
GET {{Restaurants_Api_HostAddress}}/api/restaurants?searchPhrase=group&pageSize=10&pageNumber=1
//Authorization: Bearer {{token}}
Accept: application/json

### Get restaurant by id
GET {{Restaurants_Api_HostAddress}}/api/restaurants/1
Authorization: Bearer {{token}}
Content-Type: application/json

### Delete restaurant by id
DELETE {{Restaurants_Api_HostAddress}}/api/restaurants/11
Authorization: Bearer {{token}}
Content-Type: application/json

### Update restaurant by id
PATCH {{Restaurants_Api_HostAddress}}/api/restaurants/9
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Owner Create",
  "description": "This is test to try update using admin",
  "category": "Malay",
  "hasDelivery": true,
  "contactEmail": "info@test.com",
  "contactNumber": "1234567",
  "city": "Damansara",
  "street": "Bukit Bintang",
  "postalCode": "12345"
}


### Create restaurant
POST {{Restaurants_Api_HostAddress}}/api/restaurants
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Owner2 Restaurant2",
  "description": "This is test for user resources part",
  "category": "Malay",
  "hasDelivery": true,
  "contactEmail": "info@test.com",
  "contactNumber": "1234567",
  "city": "Damansara",
  "street": "Bukit Bintang",
  "postalCode": "12345"
}

###
PATCH {{Restaurants_Api_HostAddress}}/api/restaurants/4
Accept: application/json

### -------- Dish ----------------
### 

GET {{Restaurants_Api_HostAddress}}/api/restaurant/1/dishes
Authorization: Bearer {{token}}
Content-Type: application/json

### ------ Identity ----------

### Register User
POST {{Restaurants_Api_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email" : "owner2@gmail.com",
  "password" : "Password1!"
}

### Login User
POST {{Restaurants_Api_HostAddress}}/api/identity/login
Content-Type: application/json

{
"email" : "owner@gmail.com",
"password" : "Password1!"
}


###
PATCH {{Restaurants_Api_HostAddress}}/api/identity/user
Authorization: Bearer {{token}}
Content-Type: application/json


{
  "Nationality" : "Malaysia",
  "DateOfBirth" : "2026-02-04"
}


###
PATCH {{Restaurants_Api_HostAddress}}/api/identity/userRole
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userEmail": "owner2@gmail.com",
  "roleName": "Owner"
}


