@Restaurants_Api_HostAddress = http://localhost:5204

@token = CfDJ8NWx4kvxRyZKrLy7i82zb4HeD5v4ckzdECBVF_ak0ctRiZJcbrHyvlPe483oe0Q6yMGVnrs4aWc2uYsgj95qkLcMRh6jFczlvmCZf8PYb5QLxjA2dvD0ra0tXqn8F9wOC6_UkHLL-FKWnt-JHmEwxhyUFwMCx1VBu5Dlg334NtRcW9jzZ4wqHz7evLdBkdnsqc_nkP6em66o94cfBWpPc7I1qlcdlMsNC01qaO0URgq02FGaxo6UI-mx8X4uDUobVS8LMlM5Q7bEAJbZ7f4Iua5KKYYibOPl1Y2TXsJJ5oRibReO_pfQbDUMnEwJdvnG-lxtFb-E028_HwQUymQ0OPD8n1WTYUM4qhNpZTirKu3tiy_A31l8_5HB-gPyrwakJOzIkE6bTjhybQcsJVZJl9ccu8m15HRQZLD_XKmt5mg5nW3IBoHodcVFkWvLTUGJX2HORlMsI72jt33Tn8eOg-fBavKdk8gAZpZ-1ShXA4HqYzCzQNyZn5WXug1PcCr3AfMMq7pCvA4_G3FcrCQmRu5dojrUrJgm9OJYgmGixJJ-2JCFdm_F0PV8azm25qrdRY9FPzD4u8TDm8KwvzizF78IszMkDWqpPfCRoWKx-YuLz8RFmei7wH8FmXvh7XymClbudx-nnZOxTSLZ-ciMB7OhMg9QRxPgJbech8h__GX5lJ7493wwQtl2IecNb75nqqJHe6UIVRz6yTpjAKQUTUaJV2dic55xLPowKaoM8pMkrnUNUrS3KdV2h3gBDmJKmLeTRKRLm_lNt90yKOI7qcwfyJ-QQmQ6JgNCUIUGqVQp

###
GET {{Restaurants_Api_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Accept: application/json

###
GET {{Restaurants_Api_HostAddress}}/api/restaurants/1
Authorization: Bearer {{token}}
Content-Type: application/json


###
POST {{Restaurants_Api_HostAddress}}/api/restaurants
Content-Type: application/json

###
PATCH {{Restaurants_Api_HostAddress}}/api/restaurants/4
Accept: application/json

### -------- Dish ----------------
### 

GET {{Restaurants_Api_HostAddress}}/api/restaurant/1/dishes
Authorization: Bearer {{token}}
Content-Type: application/json

### ------ Identity ----------

###
POST {{Restaurants_Api_HostAddress}}/api/identity/login
Content-Type: application/json

{
"email" : "testuser2@gmail.com",
"password" : "Password1!"
}


###
PATCH {{Restaurants_Api_HostAddress}}/api/identity/user
Authorization: Bearer {{token}}
Content-Type: application/json


{
  "Nationality" : "Malaysia",
  "DateOfBirth" : "2026-02-04"
}


